### PR TITLE
Ignore super() in no-unused-expressions

### LINKED ISSUE #21: "no-unused-expressions" catches super() as an unused statement
When creating a class in es6 there are often times for extension when I used 'super'. The no-unused-expressions catches this as an unused expression and should probably be an option if not outright defaulted to always being ignored.

### PR DESCRIPTION
**Pull request by macklinu**
Resolves #21

### CODE REVIEW

**Comment by graingert** [comment]
can you add a test that ensures `; super.method();` still trips the rule?

**Comment by graingert** [comment]
(also rebase for the tests to pass)

**Comment by macklinu** [comment]
Good suggestion on that test case - will push that up with any tweaks to the rule that may need to be made. 👍

**Comment by macklinu** [comment]
Actually, just to clarify your request, are you asking to add a test that ensures the following code produces an error?

```js
class MyClass extends SuperClass {
  constructor(arg) {
    super(arg);
    super.method();
  }
}
```

**Comment by graingert** [comment]
@macklinu yes

**Comment by macklinu** [comment]
Rebased and pushed up that test case.

**Pull request merged**
